### ISSUE TITLE
Load Service Manager Specific Variables

### ISSUE THREAD

**Issue by IgorOhrimenko** [bdellegrazie/ansible-role-prometheus_exporter#2]
ansible-playbook 2.9.0
ansible-role-prometheus_exporter 1.1.1
```
TASK [bdellegrazie.ansible-role-prometheus_exporter : Load Service Manager Specific Variables] ********************************************************************************************************************
task path: /home/user/ansible-playbooks/roles/bdellegrazie.ansible-role-prometheus_exporter/tasks/main.yml:16
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 650, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/include_vars.py", line 95, in run
    self._set_args()
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/include_vars.py", line 53, in _set_args
    self.source_file = self._task.args.get('_raw_params').rstrip('\n')
AttributeError: 'list' object has no attribute 'rstrip'

fatal: [server]: FAILED! => {
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
...ignoring
```

**Comment by bdellegrazie** [comment]
I'll take a look at this tonight
